[json-utils] implement file lock for write_json function (#4294)
The write_json might be called from different threads and even from
different processes concurrently. In some platforms, this has been
causing intermittent failures like:

> multipass delete foo-bar
Could not commit transactional file; filename:
C:/Users/musti/AppData/Local/Temp/multipass-test/data/multipassd-vm-instances.json,
error: Access is denied

This patch fixes that by introducing an interprocess lock file to
synchronize writes on per-file basis. Also, the patch introduces a retry
logic with backoff that includes a jitter to decrease the chances of a
.commit() collision even further.

This is mostly beneficial for Windows, but makes the whole process safer
for the other platforms as well.

The lockfile guarantees that no concurrent write_json can happen to the
same file at the same time. The retry logic ensures that the commit
would be retried if the file has been locked by an external factor
(e.g., Windows indexing, antiviruses, etc).

Added some logging to help with troubleshooting.

MULTI-2159