[tests/mock_logger] Add substr as Description() for distinction
Right now, it's hard to tell which expect_log call is failed to
be satisfied because the output is ambiguous:

 error: Actual function call count doesn't match EXPECT_CALL(*this, log(lvl, _, HasSubstr(substr)))...
         Expected: to be called once
           Actual: never called - unsatisfied and active

The patch fixes that by utilizing the matcher description:

 error: Actual function "my expected log string" call count doesn't match EXPECT_CALL(*this, log(lvl, _, HasSubstr(substr)))...
         Expected: to be called once
           Actual: never called - unsatisfied and active

Signed-off-by: Mustafa Kemal Gilor <mustafa.gilor@canonical.com>