[rpc] compile with /bigobj
MSVC has started to complain, which is fixed by passing the /bigobj flag.

C:\multipass-private\build\gen\multipass\rpc\multipass.grpc.pb.cc :
fatal error C1128: number of sections exceeded object file format limit:
compile with /bigobj